default:
    @just --list

# Aliases
alias ss := services
alias st := services-stop
alias sr := restart
alias sc := services-clean
alias sca := services-clean-all
alias dbc := db-clear
alias dbs := db-seed
alias dbr := db-reset
alias dbtc := db-topics-clear
alias dbts := db-topics-seed
alias dbtr := db-topics-reset
alias dbac := db-analysis-clear
alias dbas := db-analysis-seed
alias dbar := db-analysis-reset
alias dbsc := db-seed-config
alias dbcd := db-clean-demo
alias dbsd := db-seed-demo
alias dbrd := db-reset-demo
alias dbfs := db-full-seed
alias dbfr := db-full-reset
alias dbnr := db-nuclear-reset
alias dbmf := db-migrate-fresh
alias f := fmt
alias fc := fmt-check
alias tc := typecheck
alias tcs := typecheck-strict

SERVICES := "postgres nats worker api dashboard nginx"

# Reinstall UV venv and all dependencies locally
[group: 'Development']
rds:
    rm -rf .venv
    uv venv --python 3.13
    uv sync --all-groups

# Install dependencies
[group: 'Development']
install-dev:
    @echo "Installing dependencies..."
    uv sync --all-groups

# Upgrade dependencies
[group: 'Development']
upgrade:
    @echo "Updating dependencies..."
    uv lock --upgrade --all-groups

# Start services (production mode)
[group: 'Services']
services:
    @echo "Starting services (postgres nats worker api dashboard nginx)..."
    docker compose up -d postgres nats worker api dashboard nginx
    @echo "Services started."
    @echo "🌐 Available at: http://localhost"
    @echo "📱 Telegram WebApp: http://localhost/webapp"
    @echo "📊 Dashboard: http://localhost/dashboard"
    @echo "🔗 Webhook URL: http://localhost/webhook/telegram"

# Start services in development mode with watch
[group: 'Services']
services-dev:
    @echo "Starting services in development mode with file watching..."
    docker compose watch
    @echo "Restarting nginx to refresh connections..."
    docker restart task-tracker-nginx || true

# Start specific service in development mode
[group: 'Services']
dev SERVICE:
    @echo "Starting {{SERVICE}} in development mode..."
    docker compose watch {{SERVICE}}

# Rebuild specific service
[group: 'Services']
rebuild SERVICE:
    @echo "Rebuilding {{SERVICE}}..."
    COMPOSE_BAKE=true docker compose build {{SERVICE}} --no-cache
    docker compose up -d {{SERVICE}}

# Restart specific service (useful for nginx DNS cache refresh)
[group: 'Services']
restart SERVICE:
    @echo "Restarting {{SERVICE}}..."
    docker compose restart {{SERVICE}}

# Stop services
[group: 'Services']
services-stop:
    @echo "Stopping services..."
    docker compose down postgres nats worker api dashboard nginx
    @echo "Services stopped."

# Full clean services without volumes
[group: 'Services']
services-clean:
    @echo "Stopping and removing services containers..."
    docker compose down
    @echo "Services containers removed."

# Full clean services with images removal
[group: 'Services']
services-clean-all:
    @echo "Stopping and removing services containers and images..."
    docker compose down --rmi all
    @echo "Services containers and images removed."

# Run Alembic migrations
[group: 'Database']
alembic-up:
    @echo "Applying database migrations..."
    uv run alembic upgrade head

# Create alembic autogenerated migration
[group: 'Database']
alembic-auto *ARGS:
    @echo "Creating database migration..."
    uv run alembic revision --autogenerate {{ARGS}}

# Complete database reset (stop services, clean volumes, restart postgres, run migrations)
[group: 'Database']
db-nuclear-reset:
    @echo "💣 Nuclear database reset initiated..."
    @just services-stop
    @echo "🗑️  Removing database volumes..."
    @docker compose down -v
    @echo "🐘 Starting postgres..."
    @docker compose up -d postgres
    @echo "⏳ Waiting for postgres to be ready..."
    @sleep 5
    @docker compose exec postgres pg_isready -U postgres -d tasktracker || sleep 3
    @echo "🔄 Running migrations..."
    @just alembic-up
    @echo "✅ Database reset complete! Clean slate ready."

# Fresh migration (ensure postgres is running and apply migrations)
[group: 'Database']
db-migrate-fresh:
    @echo "🔄 Applying fresh migrations..."
    @docker compose up -d postgres
    @echo "⏳ Waiting for postgres to be ready..."
    @sleep 3
    @docker compose exec postgres pg_isready -U postgres -d tasktracker || sleep 2
    @just alembic-up
    @echo "✅ Migrations applied successfully!"

# Format code: organize imports + format style
[group: 'Quality']
fmt PATH='backend':
    @echo "🎨 Formatting {{PATH}}..."
    @uv run ruff check {{PATH}} --select I,F401,UP --fix --unsafe-fixes --show-fixes
    @uv run ruff format {{PATH}}
    @echo "✨ Format complete!"

# Check formatting without changes (CI)
[group: 'Quality']
fmt-check PATH='backend':
    @echo "🔍 Checking format on {{PATH}}..."
    @uv run ruff check {{PATH}} --select I,F401,UP
    @uv run ruff format {{PATH}} --check
    @echo "✅ Format check passed!"

# Run mypy type checking
[group: 'Quality']
typecheck PATH='.':
    @echo "🔎 Running mypy type checking on {{PATH}}..."
    @cd backend && uv run mypy {{PATH}}
    @echo "✅ Type check passed!"

# Run strict mypy type checking (show all errors)
[group: 'Quality']
typecheck-strict PATH='.':
    @echo "🔬 Running strict mypy type checking on {{PATH}}..."
    @cd backend && uv run mypy {{PATH}} --strict --show-error-context
    @echo "✅ Strict type check passed!"

# Serve MkDocs documentation locally with live reload
[group: 'Documentation']
docs:
    @echo "Serving documentation with live reload..."
    uv run --group docs mkdocs serve --config-file mkdocs.yml --dev-addr 127.0.0.1:8081 --livereload

# Serve learning documentation (окрема від основної docs)
[group: 'Documentation']
learn:
    @echo "📚 Serving Frontend Learning documentation..."
    @echo "→ http://127.0.0.1:8082"
    uv run --group docs mkdocs serve --config-file docs/learning/mkdocs.yml --dev-addr 127.0.0.1:8082 --livereload

# ═══════════════════════════════════════════════════════════════════════════
# STORYBOOK
# ═══════════════════════════════════════════════════════════════════════════

# Run Storybook component library
[group: 'Frontend']
storybook:
    @echo "📚 Starting Storybook..."
    @echo "→ http://localhost:6006"
    cd frontend && npm run storybook

# Build static Storybook
[group: 'Frontend']
storybook-build:
    @echo "📦 Building static Storybook..."
    cd frontend && npm run build-storybook
    @echo "✅ Built to frontend/storybook-static/"

# Run Storybook tests (requires Storybook running on :6006)
[group: 'Frontend']
storybook-test:
    @echo "🧪 Running Storybook tests..."
    cd frontend && npm run test:storybook

# Run Storybook tests in CI mode
[group: 'Frontend']
storybook-test-ci:
    @echo "🧪 Running Storybook tests (CI mode)..."
    cd frontend && npm run test:storybook:ci

# Check Storybook coverage (components with missing stories)
[group: 'Frontend']
story-check:
    @echo "📋 Checking Storybook coverage..."
    cd frontend && npm run story:check:fix

# Check Storybook coverage (brief output)
[group: 'Frontend']
story-check-brief:
    @echo "📋 Checking Storybook coverage..."
    cd frontend && npm run story:check

# Clear all test data from database
[group: 'Database']
db-clear:
    @echo "Clearing database..."
    uv run python scripts/seed_db.py --clear

# Seed test data into database
[group: 'Database']
db-seed COUNT="50":
    @echo "Seeding {{COUNT}} tasks..."
    uv run python scripts/seed_db.py --seed --count {{COUNT}}

# Clear and seed database (fresh start)
[group: 'Database']
db-reset COUNT="50":
    @echo "Resetting database with {{COUNT}} tasks..."
    uv run python scripts/seed_db.py --clear --seed --count {{COUNT}}

# Clear topics, atoms, messages and relationships
[group: 'Database']
db-topics-clear:
    @echo "Clearing topics, atoms, and messages..."
    cd backend && uv run python scripts/seed_topics_atoms.py --clear

# Seed topics, atoms, messages and relationships
[group: 'Database']
db-topics-seed TOPICS="5" ATOMS="10" MESSAGES="20":
    @echo "Seeding {{TOPICS}} topics with {{ATOMS}} atoms and {{MESSAGES}} messages each..."
    cd backend && uv run python scripts/seed_topics_atoms.py --seed --topics {{TOPICS}} --atoms {{ATOMS}} --messages {{MESSAGES}}

# Clear and seed topics/atoms (fresh start)
[group: 'Database']
db-topics-reset TOPICS="5" ATOMS="10" MESSAGES="20":
    @echo "Resetting topics with {{TOPICS}} topics, {{ATOMS}} atoms, {{MESSAGES}} messages..."
    cd backend && uv run python scripts/seed_topics_atoms.py --clear --seed --topics {{TOPICS}} --atoms {{ATOMS}} --messages {{MESSAGES}}

# Seed topics, atoms, and messages for testing
[group: 'Database']
seed-topics COUNT="5":
    @echo "Seeding {{COUNT}} topics with atoms and messages..."
    uv run python scripts/seed_topics_atoms.py --seed --topics {{COUNT}}

# Clear all topics, atoms, and messages
[group: 'Database']
clear-topics:
    @echo "Clearing topics, atoms, and messages..."
    uv run python scripts/seed_topics_atoms.py --clear

# Reset topics data (clear + seed)
[group: 'Database']
reset-topics COUNT="5":
    @echo "Resetting topics data..."
    uv run python scripts/seed_topics_atoms.py --clear --seed --topics {{COUNT}}

# Clear Analysis System data (providers, agents, tasks, runs, proposals)
[group: 'Database']
db-analysis-clear:
    @echo "Clearing Analysis System data..."
    cd backend && uv run python scripts/seed_analysis_system.py --clear

# Seed Analysis System data
[group: 'Database']
db-analysis-seed RUNS="10" PROPOSALS="30":
    @echo "Seeding Analysis System: {{RUNS}} runs, {{PROPOSALS}} proposals..."
    cd backend && uv run python scripts/seed_analysis_system.py --seed --runs {{RUNS}} --proposals {{PROPOSALS}}

# Clear and seed Analysis System (fresh start)
[group: 'Database']
db-analysis-reset RUNS="10" PROPOSALS="30":
    @echo "Resetting Analysis System with {{RUNS}} runs, {{PROPOSALS}} proposals..."
    cd backend && uv run python scripts/seed_analysis_system.py --clear --seed --runs {{RUNS}} --proposals {{PROPOSALS}}

# Seed config data (Users, Source, Provider, Agent, Project, Topics)
[group: 'Database']
db-seed-config:
    @echo "🔧 Seeding config data (critical for system operation)..."
    cd backend && uv run python scripts/seed_config.py
    @echo "✅ Config data seeded!"

# Clean demo data (topics, atoms, messages) - preserving config
[group: 'Database']
db-clean-demo:
    @echo "🗑️  Cleaning demo data..."
    cd backend && uv run python scripts/db_clean_all.py
    @echo "✅ Demo data cleaned!"

# Seed demo data (anonymized Ukrainian messages + atoms)
[group: 'Database']
db-seed-demo:
    @echo "🎭 Seeding demo data (75 messages, 25 atoms, 7 topics)..."
    cd backend && uv run python scripts/seed_demo_uk.py
    @echo "✅ Demo data seeded!"

# Clean and reseed demo data (quick reset)
[group: 'Database']
db-reset-demo:
    @echo "🔄 Resetting demo data..."
    @just db-clean-demo
    @just db-seed-config
    @just db-seed-demo
    @echo "✅ Demo data reset complete!"

# Seed EVERYTHING: tasks + topics + analysis system
[group: 'Database']
db-full-seed:
    @echo "🌱 Full database seeding..."
    @just db-seed 50
    @just db-topics-seed 5 10 20
    @just db-analysis-seed 10 30
    @echo "✅ Complete database populated!"

# Clear and seed EVERYTHING (nuclear reset + config + demo)
[group: 'Database']
db-full-reset:
    @echo "🗑️  Nuclear database reset..."
    @just db-clear
    @just db-topics-clear
    @just db-analysis-clear
    @echo "🔧 Seeding config..."
    @just db-seed-config
    @echo "🎭 Seeding demo data..."
    @just db-seed-demo
    @echo "✅ Complete database reset with demo data finished!"

# Run tests
[group: 'Testing']
test:
    @echo "Running tests..."
    uv run python -m pytest

# Run API tests for atoms
[group: 'Testing']
test-atoms:
    @echo "Running atoms API tests..."
    uv run pytest tests/api/test_atoms.py -v

# Run all tests with coverage
[group: 'Testing']
test-all:
    @echo "Running all tests with coverage..."
    uv run pytest --cov=app --cov-report=term-missing

# Run E2E tests (Playwright)
[group: 'Testing']
e2e *ARGS:
    @echo "🎭 Running E2E tests..."
    cd frontend && npx playwright test {{ARGS}}

# Run E2E tests on chromium only (faster)
[group: 'Testing']
e2e-fast *ARGS:
    @echo "🎭 Running E2E tests (chromium only)..."
    cd frontend && npx playwright test --project=chromium {{ARGS}}

# Run E2E tests with UI mode
[group: 'Testing']
e2e-ui:
    @echo "🎭 Opening Playwright UI..."
    cd frontend && npx playwright test --ui

# Install Playwright browsers
[group: 'Testing']
e2e-install:
    @echo "📦 Installing Playwright browsers..."
    cd frontend && npx playwright install

# ═══════════════════════════════════════════════════════════════════════════
# FRONTEND
# ═══════════════════════════════════════════════════════════════════════════

# Install frontend dependencies
[group: 'Frontend']
front-install:
    @echo "📦 Installing frontend dependencies..."
    cd frontend && npm install
    @echo "✅ Frontend dependencies installed!"

# Run ESLint on frontend (warnings only - no fail)
[group: 'Frontend']
lint:
    @echo "🔍 Running ESLint on frontend..."
    cd frontend && ESLINT_USE_FLAT_CONFIG=false npx eslint src --ext .ts,.tsx || true
    @echo "ℹ️  Lint complete (check output above for issues)"

# Run ESLint strict (fails on errors)
[group: 'Frontend']
lint-strict:
    @echo "🔍 Running ESLint strict mode..."
    cd frontend && ESLINT_USE_FLAT_CONFIG=false npx eslint src --ext .ts,.tsx --max-warnings 0
    @echo "✅ Lint passed!"

# Run ESLint with auto-fix
[group: 'Frontend']
lint-fix:
    @echo "🔧 Running ESLint with auto-fix..."
    cd frontend && ESLINT_USE_FLAT_CONFIG=false npx eslint src --ext .ts,.tsx --fix
    @echo "✅ Lint fix complete!"

# Run frontend TypeScript check
[group: 'Frontend']
front-typecheck:
    @echo "🔎 Running TypeScript check on frontend..."
    cd frontend && npx tsc --noEmit
    @echo "✅ Frontend TypeScript check passed!"

# Run frontend unit tests
[group: 'Frontend']
front-test:
    @echo "🧪 Running frontend unit tests..."
    cd frontend && npm run test:run
    @echo "✅ Frontend tests passed!"

# ═══════════════════════════════════════════════════════════════════════════
# API CONTRACTS
# ═══════════════════════════════════════════════════════════════════════════

# Export OpenAPI schema from backend
[group: 'Contracts']
api-export:
    @echo "📤 Exporting OpenAPI schema..."
    cd backend && uv run python scripts/export_openapi.py
    @echo "✅ Schema exported to contracts/openapi.json"

# Generate TypeScript types from OpenAPI
[group: 'Contracts']
api-generate:
    @echo "🔄 Generating TypeScript types..."
    cd frontend && npm run generate:api
    @echo "✅ Types generated in frontend/src/shared/api/"

# Full contract sync (export + generate)
[group: 'Contracts']
api-sync:
    @just api-export
    @just api-generate
    @echo "🎉 API contracts synchronized!"

# ═══════════════════════════════════════════════════════════════════════════
# WIFI SHARING (macOS)
# ═══════════════════════════════════════════════════════════════════════════

# Toggle WiFi access (start/stop services)
[group: 'WiFi']
wifi:
    #!/usr/bin/env bash
    if docker compose ps nginx --format "{{{{.State}}}}" 2>/dev/null | grep -q "running"; then
        echo "📡 Stopping WiFi access..."
        just services-stop
        echo "✅ WiFi access disabled"
    else
        echo "📡 Starting WiFi access..."
        docker compose up -d postgres nats worker api dashboard nginx
        echo ""
        echo "✅ WiFi access enabled!"
        echo ""
        echo "📱 Access from other devices:"
        echo "   http://$(ipconfig getifaddr en0 || echo 'N/A')"
    fi

# ═══════════════════════════════════════════════════════════════════════════
# PROJECT GENERATION
# ═══════════════════════════════════════════════════════════════════════════

# Generate project from YAML fixture
[group: 'Project Generation']
generate-project FIXTURE OUTPUT=".":
    @echo "🚀 Generating project from fixture..."
    uv run python scripts/project-generator/generator.py {{FIXTURE}} {{OUTPUT}}

# Generate FeodalMe project
[group: 'Project Generation']
generate-feudalme OUTPUT="../":
    @echo "🏰 Generating FeodalMe project..."
    uv run python scripts/project-generator/generator.py scripts/project-generator/fixtures/feudalme.yaml {{OUTPUT}}
    @echo ""
    @echo "✅ FeodalMe project created!"
    @echo "📂 Location: {{OUTPUT}}/feudalme"

# List available fixtures
[group: 'Project Generation']
list-fixtures:
    @echo "📋 Available project fixtures:"
    @ls -1 scripts/project-generator/fixtures/*.yaml | xargs basename -s .yaml

# ═══════════════════════════════════════════════════════════════════════════
# DATABASE PROJECTS SEED
# ═══════════════════════════════════════════════════════════════════════════

# Seed FeodalMe project into database
[group: 'Database']
db-seed-feudalme:
    @echo "🏰 Seeding FeodalMe project..."
    cd backend && uv run python scripts/seed_feudalme_project.py

# Delete FeodalMe project from database
[group: 'Database']
db-delete-feudalme:
    @echo "🗑️  Deleting FeodalMe project..."
    cd backend && uv run python scripts/seed_feudalme_project.py --delete
