[project]
name = "task-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic-postgresql-enum>=1.8.0",
    "alembic>=1.16.5",
    "fastapi[all]>=0.116.1",
    "loguru>=0.7.3",
    "sqlalchemy>=2.0.43",
    "pydantic-settings>=2.10.1",
    "taskiq>=0.11.18",
    "python-telegram-bot>=22.3",
    "typer>=0.16.1",
]

[dependency-groups]
dev = [
    "mypy>=1.17.1",
    "ruff>=0.12.11",
]
test = [
    "pytest-asyncio>=1.1.0",
]
