openapi: 3.0.3
info:
  title: Task Monitoring Metrics API
  description: Real-time health metrics for background task execution
  version: 1.0.0

paths:
  /api/v1/monitoring/metrics:
    get:
      summary: Get task execution health metrics
      description: |
        Returns aggregated health metrics for all task types, showing counts by status
        (active, queued, success, failed) for the last 24 hours.

        Corresponds to FR-001 (display real-time health status) and FR-002 (show execution counts).
      operationId: getTaskMetrics
      tags:
        - monitoring
      parameters:
        - name: time_window
          in: query
          description: Time window in hours for metrics calculation
          required: false
          schema:
            type: integer
            default: 24
            minimum: 1
            maximum: 168
            example: 24
      responses:
        '200':
          description: Successfully retrieved metrics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MonitoringMetricsResponse'
              examples:
                typical:
                  value:
                    time_window_hours: 24
                    generated_at: "2025-10-27T12:00:00Z"
                    metrics:
                      - task_name: "extract_knowledge_from_messages_task"
                        total_executions: 150
                        pending: 5
                        running: 2
                        success: 140
                        failed: 3
                        avg_duration_ms: 1250
                        success_rate: 93.33
                      - task_name: "score_message_task"
                        total_executions: 500
                        pending: 10
                        running: 5
                        success: 480
                        failed: 5
                        avg_duration_ms: 320
                        success_rate: 96.00
        '400':
          description: Invalid time window parameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "Invalid time_window: must be between 1 and 168 hours"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    MonitoringMetricsResponse:
      type: object
      required:
        - time_window_hours
        - generated_at
        - metrics
      properties:
        time_window_hours:
          type: integer
          description: Time window used for metrics calculation
          example: 24
        generated_at:
          type: string
          format: date-time
          description: Timestamp when metrics were generated (ISO 8601 UTC)
          example: "2025-10-27T12:00:00Z"
        metrics:
          type: array
          description: Per-task-type health metrics
          items:
            $ref: '#/components/schemas/TaskMetrics'

    TaskMetrics:
      type: object
      required:
        - task_name
        - total_executions
        - pending
        - running
        - success
        - failed
        - avg_duration_ms
        - success_rate
      properties:
        task_name:
          type: string
          description: Task function name
          example: "extract_knowledge_from_messages_task"
        total_executions:
          type: integer
          description: Total executions in time window
          minimum: 0
          example: 150
        pending:
          type: integer
          description: Count of pending (queued) tasks
          minimum: 0
          example: 5
        running:
          type: integer
          description: Count of currently running tasks
          minimum: 0
          example: 2
        success:
          type: integer
          description: Count of successfully completed tasks
          minimum: 0
          example: 140
        failed:
          type: integer
          description: Count of failed tasks
          minimum: 0
          example: 3
        avg_duration_ms:
          type: number
          format: float
          description: Average execution duration in milliseconds (successful tasks only)
          minimum: 0
          example: 1250.5
        success_rate:
          type: number
          format: float
          description: Success rate percentage (success / total * 100)
          minimum: 0
          maximum: 100
          example: 93.33

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Human-readable error message
          example: "Invalid time_window parameter"
