"""add archive fields to atoms

Revision ID: 0a5aba48aca0
Revises: 5b920fdc142d
Create Date: 2025-11-02 18:57:08.623829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a5aba48aca0'
down_revision: Union[str, Sequence[str], None] = '5b920fdc142d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atoms', sa.Column('archived', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('atoms', sa.Column('archived_at', sa.DateTime(), nullable=True))
    op.alter_column('atoms', 'archived', server_default=None)
    op.drop_index(op.f('idx_failed_tasks_created_at'), table_name='failed_tasks')
    op.create_index('idx_failed_tasks_created_at', 'failed_tasks', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_failed_tasks_status_created'), table_name='failed_tasks')
    op.create_index('idx_failed_tasks_status_created', 'failed_tasks', ['status', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_task_logs_composite'), table_name='task_execution_logs')
    op.create_index('idx_task_logs_composite', 'task_execution_logs', ['task_name', 'status', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('idx_task_logs_created_at'), table_name='task_execution_logs')
    op.create_index('idx_task_logs_created_at', 'task_execution_logs', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_logs_created_at', table_name='task_execution_logs', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_task_logs_created_at'), 'task_execution_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_task_logs_composite', table_name='task_execution_logs', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_task_logs_composite'), 'task_execution_logs', ['task_name', 'status', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_failed_tasks_status_created', table_name='failed_tasks', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_failed_tasks_status_created'), 'failed_tasks', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_failed_tasks_created_at', table_name='failed_tasks', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_failed_tasks_created_at'), 'failed_tasks', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_column('atoms', 'archived_at')
    op.drop_column('atoms', 'archived')
    # ### end Alembic commands ###
