"""add_agent_type_and_system_fields

Revision ID: 18b82dace293
Revises: 54a3cb33f2bc
Create Date: 2026-01-09 21:55:55.903276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18b82dace293'
down_revision: Union[str, Sequence[str], None] = '54a3cb33f2bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type first
    agenttype = sa.Enum('system', 'custom', name='agenttype')
    agenttype.create(op.get_bind(), checkfirst=True)

    # Add columns with server_default for existing rows
    op.add_column('agent_configs', sa.Column(
        'agent_type',
        sa.Enum('system', 'custom', name='agenttype'),
        nullable=False,
        server_default='custom'
    ))
    op.add_column('agent_configs', sa.Column(
        'is_system_prompt_locked',
        sa.Boolean(),
        nullable=False,
        server_default=sa.text('false')
    ))
    op.add_column('agent_configs', sa.Column(
        'is_output_schema_locked',
        sa.Boolean(),
        nullable=False,
        server_default=sa.text('false')
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_configs', 'is_output_schema_locked')
    op.drop_column('agent_configs', 'is_system_prompt_locked')
    op.drop_column('agent_configs', 'agent_type')

    # Drop enum type
    agenttype = sa.Enum('system', 'custom', name='agenttype')
    agenttype.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
