"""add icon field to topics

Revision ID: 4501805fe608
Revises: c3baeb03b1f2
Create Date: 2025-10-12 16:59:44.360933

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "4501805fe608"
down_revision: Union[str, Sequence[str], None] = "c3baeb03b1f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("topics", sa.Column("icon", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("topics", "icon")
    # ### end Alembic commands ###
