"""Add Telegram user fields to simple_messages

Revision ID: a08c50a937cf
Revises: cc840f79ab10
Create Date: 2025-10-07 05:15:34.351246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a08c50a937cf'
down_revision: Union[str, Sequence[str], None] = 'cc840f79ab10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simple_messages', sa.Column('telegram_user_id', sa.Integer(), nullable=True))
    op.add_column('simple_messages', sa.Column('telegram_username', sa.String(length=100), nullable=True))
    op.add_column('simple_messages', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('simple_messages', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_simple_messages_telegram_user_id'), 'simple_messages', ['telegram_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simple_messages_telegram_user_id'), table_name='simple_messages')
    op.drop_column('simple_messages', 'last_name')
    op.drop_column('simple_messages', 'first_name')
    op.drop_column('simple_messages', 'telegram_username')
    op.drop_column('simple_messages', 'telegram_user_id')
    # ### end Alembic commands ###
