"""add topic_id to messages

Revision ID: a8ec482173f8
Revises: d00f35446ee4
Create Date: 2025-10-13 13:40:36.573872

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "a8ec482173f8"
down_revision: Union[str, Sequence[str], None] = "d00f35446ee4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("topic_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_messages_topic_id"), "messages", ["topic_id"], unique=False)
    op.create_foreign_key(None, "messages", "topics", ["topic_id"], ["id"])
    op.alter_column(
        "topics",
        "color",
        existing_type=sa.VARCHAR(length=20),
        type_=sqlmodel.sql.sqltypes.AutoString(length=7),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "topics",
        "color",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=7),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.drop_index(op.f("ix_messages_topic_id"), table_name="messages")
    op.drop_column("messages", "topic_id")
    # ### end Alembic commands ###
