"""Add automation_rules table for rule engine

Revision ID: fb1269894cf9
Revises: 971fc20baa80
Create Date: 2025-10-26 18:51:04.328555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb1269894cf9'
down_revision: Union[str, Sequence[str], None] = '971fc20baa80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_rules',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=False),
    sa.Column('logic_operator', sa.String(length=3), server_default='AND', nullable=False),
    sa.Column('triggered_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('success_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_triggered', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('automation_rules')
    # ### end Alembic commands ###
