/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { ActivityDataPoint } from './activityDataPoint';
import type { ActivityPeriod } from './activityPeriod';

export interface ActivityDataResponse {
  data: ActivityDataPoint[];
  period: ActivityPeriod;
  total_messages: number;
}
