/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { ActivityPeriodMonth } from './activityPeriodMonth';
import type { ActivityPeriodYear } from './activityPeriodYear';

export interface ActivityPeriod {
  type: string;
  start: string;
  end: string;
  month?: ActivityPeriodMonth;
  year?: ActivityPeriodYear;
}
