/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Request schema for adding a Telegram group
 */
export interface AddTelegramGroupRequest {
  /** Telegram chat/group ID to add */
  group_id: number;
}
