/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { AgentConfigUpdateName } from './agentConfigUpdateName';
import type { AgentConfigUpdateDescription } from './agentConfigUpdateDescription';
import type { AgentConfigUpdateProviderId } from './agentConfigUpdateProviderId';
import type { AgentConfigUpdateModelName } from './agentConfigUpdateModelName';
import type { AgentConfigUpdateSystemPrompt } from './agentConfigUpdateSystemPrompt';
import type { AgentConfigUpdateTemperature } from './agentConfigUpdateTemperature';
import type { AgentConfigUpdateMaxTokens } from './agentConfigUpdateMaxTokens';
import type { AgentConfigUpdateIsActive } from './agentConfigUpdateIsActive';

/**
 * Schema for updating agent configuration.
 */
export interface AgentConfigUpdate {
  /** Agent name (non-empty if provided) */
  name?: AgentConfigUpdateName;
  description?: AgentConfigUpdateDescription;
  provider_id?: AgentConfigUpdateProviderId;
  /** Model name (non-empty if provided) */
  model_name?: AgentConfigUpdateModelName;
  /** System prompt (non-empty if provided) */
  system_prompt?: AgentConfigUpdateSystemPrompt;
  /** Temperature (0.0-1.0 if provided) */
  temperature?: AgentConfigUpdateTemperature;
  /** Maximum tokens (positive if provided) */
  max_tokens?: AgentConfigUpdateMaxTokens;
  is_active?: AgentConfigUpdateIsActive;
}
