/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { AgentConfigCreateDescription } from './agentConfigCreateDescription';
import type { AgentConfigCreateTemperature } from './agentConfigCreateTemperature';
import type { AgentConfigCreateMaxTokens } from './agentConfigCreateMaxTokens';

/**
 * Schema for creating new agent configuration.
 */
export interface AgentConfigCreate {
  /**
   * Agent name (required, non-empty)
   * @minLength 1
   */
  name: string;
  description?: AgentConfigCreateDescription;
  provider_id: string;
  /**
   * Model name (required, non-empty)
   * @minLength 1
   */
  model_name: string;
  /**
   * System prompt (required, non-empty)
   * @minLength 1
   */
  system_prompt: string;
  /** Temperature (0.0-1.0) */
  temperature?: AgentConfigCreateTemperature;
  /** Maximum tokens (must be positive) */
  max_tokens?: AgentConfigCreateMaxTokens;
  is_active?: boolean;
}
