/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { AgentConfigPublicDescription } from './agentConfigPublicDescription';
import type { AgentConfigPublicTemperature } from './agentConfigPublicTemperature';
import type { AgentConfigPublicMaxTokens } from './agentConfigPublicMaxTokens';

/**
 * Public schema for agent configuration responses.
 */
export interface AgentConfigPublic {
  id: string;
  name: string;
  description?: AgentConfigPublicDescription;
  provider_id: string;
  model_name: string;
  system_prompt: string;
  temperature?: AgentConfigPublicTemperature;
  max_tokens?: AgentConfigPublicMaxTokens;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}
