/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { AgentTaskAssignmentCreateAgentId } from './agentTaskAssignmentCreateAgentId';

/**
 * Schema for creating new agent-task assignment.
 */
export interface AgentTaskAssignmentCreate {
  agent_id?: AgentTaskAssignmentCreateAgentId;
  task_id: string;
  is_active?: boolean;
}
