/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Request schema for testing an agent.
 */
export interface AgentTestRequest {
  /**
   * Test prompt to send to the agent
   * @minLength 1
   * @maxLength 5000
   */
  prompt: string;
}
