/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Response schema for agent test results.
 */
export interface AgentTestResponse {
  /** UUID of the tested agent */
  agent_id: string;
  /** Name of the tested agent */
  agent_name: string;
  /** Prompt that was sent to the agent */
  prompt: string;
  /** Agent's response from LLM */
  response: string;
  /** Time taken to get response in seconds */
  elapsed_time: number;
  /** Model used for the test */
  model_name: string;
  /** Provider name */
  provider_name: string;
  /** Provider type (ollama, openai) */
  provider_type: string;
}
