/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Public schema for agent-task assignment responses.
 */
export interface AgentTaskAssignmentPublic {
  id: string;
  agent_id: string;
  task_id: string;
  is_active: boolean;
  assigned_at: string;
}
