/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Extended assignment schema with JOIN details from related entities.
 */
export interface AgentTaskAssignmentWithDetails {
  id: string;
  agent_id: string;
  task_id: string;
  is_active: boolean;
  assigned_at: string;
  agent_name: string;
  task_name: string;
  provider_name: string;
  provider_type: string;
}
