/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { TrendData } from './trendData';

/**
 * Trends for messages, atoms, topics
 */
export type AppApiV1SchemasDashboardDashboardMetricsResponseTrends = {[key: string]: TrendData};
