/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { AppApiV1SearchMessageSearchResultTopic } from './appApiV1SearchMessageSearchResultTopic';

/**
 * Search result for a message.
 */
export interface AppApiV1SearchMessageSearchResult {
  id: string;
  /** Content snippet with highlighted match (max 200 chars) */
  content_snippet: string;
  author: string;
  timestamp: string;
  /** Linked topic if available */
  topic?: AppApiV1SearchMessageSearchResultTopic;
  /** Relevance rank score */
  rank: number;
}
