/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { MessageResponse } from './messageResponse';

/**
 * Message search result with similarity score.
 */
export interface AppApiV1SemanticSearchMessageSearchResult {
  /**
   * Similarity score (0.0-1.0, higher means more similar)
   * @minimum 0
   * @maximum 1
   */
  similarity_score: number;
  message: MessageResponse;
}
