/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Actual period used for metrics
 */
export type AppApiV1SchemasDashboardDashboardMetricsResponsePeriod = typeof AppApiV1SchemasDashboardDashboardMetricsResponsePeriod[keyof typeof AppApiV1SchemasDashboardDashboardMetricsResponsePeriod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AppApiV1SchemasDashboardDashboardMetricsResponsePeriod = {
  today: 'today',
  yesterday: 'yesterday',
} as const;
