/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { AppApiV1SchemasDashboardDashboardMetricsResponsePeriod } from './appApiV1SchemasDashboardDashboardMetricsResponsePeriod';
import type { MessageStats } from './messageStats';
import type { AtomStats } from './atomStats';
import type { TopicStats } from './topicStats';
import type { AppApiV1SchemasDashboardDashboardMetricsResponseTrends } from './appApiV1SchemasDashboardDashboardMetricsResponseTrends';

/**
 * Complete dashboard metrics response.
 */
export interface AppApiV1SchemasDashboardDashboardMetricsResponse {
  /** Actual period used for metrics */
  period: AppApiV1SchemasDashboardDashboardMetricsResponsePeriod;
  /** Localized period label for UI */
  period_label: string;
  messages: MessageStats;
  atoms: AtomStats;
  topics: TopicStats;
  /** Trends for messages, atoms, topics */
  trends?: AppApiV1SchemasDashboardDashboardMetricsResponseTrends;
  /** When metrics were generated */
  generated_at: string;
}
