/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { AppApiV1SearchTopicSearchResultDescription } from './appApiV1SearchTopicSearchResultDescription';

/**
 * Search result for a topic.
 */
export interface AppApiV1SearchTopicSearchResult {
  id: string;
  name: string;
  description: AppApiV1SearchTopicSearchResultDescription;
  /** Highlighted match snippet */
  match_snippet: string;
  /** Relevance rank score */
  rank: number;
}
