/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

export interface ApproveVersionRequest { [key: string]: unknown }
