/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { AtomPublicConfidence } from './atomPublicConfidence';
import type { AtomPublicArchivedAt } from './atomPublicArchivedAt';
import type { AtomPublicMeta } from './atomPublicMeta';
import type { AtomPublicEmbedding } from './atomPublicEmbedding';

/**
 * Public schema for atom responses.
 */
export interface AtomPublic {
  id: string;
  type: string;
  title: string;
  content: string;
  confidence: AtomPublicConfidence;
  user_approved: boolean;
  archived: boolean;
  archived_at: AtomPublicArchivedAt;
  meta: AtomPublicMeta;
  embedding?: AtomPublicEmbedding;
  has_embedding?: boolean;
  created_at: string;
  updated_at: string;
}
