/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { AtomPublic } from './atomPublic';

/**
 * Paginated response schema for atoms.
 */
export interface AtomListResponse {
  items: AtomPublic[];
  total: number;
  page: number;
  page_size: number;
}
