/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { AtomCreateConfidence } from './atomCreateConfidence';
import type { AtomCreateMeta } from './atomCreateMeta';

/**
 * Schema for creating a new atom.
 */
export interface AtomCreate {
  /**
   * Type of atom (problem, solution, decision, etc.)
   * @maxLength 20
   */
  type: string;
  /**
   * Brief title summarizing the atom
   * @minLength 1
   * @maxLength 200
   */
  title: string;
  /**
   * Full content of the atomic knowledge unit
   * @minLength 1
   */
  content: string;
  /** AI confidence score (0-1, optional) */
  confidence?: AtomCreateConfidence;
  /** Whether user has explicitly approved this atom */
  user_approved?: boolean;
  /** Additional structured metadata */
  meta?: AtomCreateMeta;
}
