/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { AtomUpdateType } from './atomUpdateType';
import type { AtomUpdateTitle } from './atomUpdateTitle';
import type { AtomUpdateContent } from './atomUpdateContent';
import type { AtomUpdateConfidence } from './atomUpdateConfidence';
import type { AtomUpdateUserApproved } from './atomUpdateUserApproved';
import type { AtomUpdateArchived } from './atomUpdateArchived';
import type { AtomUpdateArchivedAt } from './atomUpdateArchivedAt';
import type { AtomUpdateMeta } from './atomUpdateMeta';

/**
 * Schema for updating an existing atom.
 */
export interface AtomUpdate {
  /** Type of atom */
  type?: AtomUpdateType;
  /** Brief title */
  title?: AtomUpdateTitle;
  /** Full content */
  content?: AtomUpdateContent;
  /** AI confidence score (0-1) */
  confidence?: AtomUpdateConfidence;
  /** User approval status */
  user_approved?: AtomUpdateUserApproved;
  /** Archive status */
  archived?: AtomUpdateArchived;
  /** Archive timestamp */
  archived_at?: AtomUpdateArchivedAt;
  /** Additional metadata */
  meta?: AtomUpdateMeta;
}
