/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { AtomVersionResponseData } from './atomVersionResponseData';
import type { AtomVersionResponseCreatedBy } from './atomVersionResponseCreatedBy';
import type { AtomVersionResponseApprovedAt } from './atomVersionResponseApprovedAt';

export interface AtomVersionResponse {
  /** Version number */
  version: number;
  /** Version snapshot data */
  data: AtomVersionResponseData;
  /** User who created version */
  created_by?: AtomVersionResponseCreatedBy;
  /** Approval status */
  approved?: boolean;
  id: number;
  atom_id: string;
  created_at: string;
  approved_at?: AtomVersionResponseApprovedAt;
}
