/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { AtomStatsByType } from './atomStatsByType';

/**
 * Atom statistics by type and status.
 */
export interface AtomStats {
  /**
   * Total atoms in period
   * @minimum 0
   */
  total: number;
  /**
   * Atoms awaiting review (user_approved=false)
   * @minimum 0
   */
  pending_review: number;
  /**
   * Approved atoms (user_approved=true)
   * @minimum 0
   */
  approved: number;
  /** Count by atom type */
  by_type?: AtomStatsByType;
}
