/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { EntitiesDetail } from './entitiesDetail';
import type { KeywordDetail } from './keywordDetail';
import type { AtomsDetailEmbedding } from './atomsDetailEmbedding';
import type { AtomsDetailSimilarMessages } from './atomsDetailSimilarMessages';

/**
 * Atoms extracted from message.
 */
export interface AtomsDetail {
  entities: EntitiesDetail;
  keywords: KeywordDetail[];
  embedding?: AtomsDetailEmbedding;
  similarMessages?: AtomsDetailSimilarMessages;
}
