/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { AutomationTrendPoint } from './automationTrendPoint';

/**
 * Response schema for automation trends over time.
 */
export interface AutomationTrendsResponse {
  /** Time period filter applied (7d, 30d, 90d) */
  period: string;
  /** Daily trend data points */
  data: AutomationTrendPoint[];
}
