/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { AutomationRuleCreateDescription } from './automationRuleCreateDescription';
import type { RuleAction } from './ruleAction';
import type { LogicOperator } from './logicOperator';

/**
 * Schema for creating a new automation rule.
 */
export interface AutomationRuleCreate {
  /**
   * Unique rule name
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /** Rule description */
  description?: AutomationRuleCreateDescription;
  /** Rule enabled status */
  enabled?: boolean;
  /**
   * Rule priority
   * @minimum 0
   * @maximum 100
   */
  priority?: number;
  /** Action to execute */
  action: RuleAction;
  /**
   * JSON-encoded conditions
   * @minLength 1
   */
  conditions: string;
  /** Logic operator */
  logic_operator?: LogicOperator;
}
