/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { AutomationRulePublic } from './automationRulePublic';

/**
 * Response schema for paginated rule listing.
 */
export interface AutomationRuleListResponse {
  rules: AutomationRulePublic[];
  total: number;
  page: number;
  page_size: number;
}
