/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { AutomationRulePublicDescription } from './automationRulePublicDescription';
import type { RuleAction } from './ruleAction';
import type { LogicOperator } from './logicOperator';
import type { AutomationRulePublicLastTriggered } from './automationRulePublicLastTriggered';
import type { AutomationRulePublicCreatedAt } from './automationRulePublicCreatedAt';
import type { AutomationRulePublicUpdatedAt } from './automationRulePublicUpdatedAt';

/**
 * Public schema for automation rule responses.
 */
export interface AutomationRulePublic {
  id: number;
  name: string;
  description: AutomationRulePublicDescription;
  enabled: boolean;
  priority: number;
  action: RuleAction;
  conditions: string;
  logic_operator: LogicOperator;
  triggered_count: number;
  success_count: number;
  last_triggered: AutomationRulePublicLastTriggered;
  created_at: AutomationRulePublicCreatedAt;
  updated_at: AutomationRulePublicUpdatedAt;
}
