/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Response schema for automation dashboard statistics.
 */
export interface AutomationStatsResponse {
  /**
   * Percentage of versions auto-approved (0-100)
   * @minimum 0
   * @maximum 100
   */
  auto_approval_rate: number;
  /**
   * Number of pending versions awaiting review
   * @minimum 0
   */
  pending_versions_count: number;
  /**
   * Total number of automation rules
   * @minimum 0
   */
  total_rules_count: number;
  /**
   * Number of enabled automation rules
   * @minimum 0
   */
  active_rules_count: number;
}
