/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { AutomationRuleUpdateName } from './automationRuleUpdateName';
import type { AutomationRuleUpdateDescription } from './automationRuleUpdateDescription';
import type { AutomationRuleUpdateEnabled } from './automationRuleUpdateEnabled';
import type { AutomationRuleUpdatePriority } from './automationRuleUpdatePriority';
import type { AutomationRuleUpdateAction } from './automationRuleUpdateAction';
import type { AutomationRuleUpdateConditions } from './automationRuleUpdateConditions';
import type { AutomationRuleUpdateLogicOperator } from './automationRuleUpdateLogicOperator';

/**
 * Schema for updating an existing automation rule.
 */
export interface AutomationRuleUpdate {
  /** Rule name */
  name?: AutomationRuleUpdateName;
  /** Rule description */
  description?: AutomationRuleUpdateDescription;
  /** Rule enabled status */
  enabled?: AutomationRuleUpdateEnabled;
  /** Rule priority */
  priority?: AutomationRuleUpdatePriority;
  /** Action to execute */
  action?: AutomationRuleUpdateAction;
  /** JSON-encoded conditions */
  conditions?: AutomationRuleUpdateConditions;
  /** Logic operator */
  logic_operator?: AutomationRuleUpdateLogicOperator;
}
