/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Single data point for automation trends.
 */
export interface AutomationTrendPoint {
  /** Date in ISO format (YYYY-MM-DD) */
  date: string;
  /**
   * Number of approved versions on this date
   * @minimum 0
   */
  approved: number;
  /**
   * Number of rejected versions on this date
   * @minimum 0
   */
  rejected: number;
  /**
   * Number of manually reviewed versions on this date
   * @minimum 0
   */
  manual: number;
}
