/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Request schema for batch embedding operation.
 */
export interface BatchEmbedRequest {
  /** List of message UUIDs to embed */
  message_ids: string[];
  /** LLMProvider UUID to use for embedding generation */
  provider_id: string;
}
