/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Request schema for batch atom embedding operation.
 */
export interface BatchEmbedAtomsRequest {
  /** List of atom UUIDs to embed */
  atom_ids: string[];
  /** LLMProvider UUID to use for embedding generation */
  provider_id: string;
}
