/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Response schema for batch embedding operation.
 */
export interface BatchEmbedResponse {
  /** Background task ID for tracking progress */
  task_id: string;
  /** Number of items queued for embedding */
  count: number;
  /** Provider ID used for embedding */
  provider_id: string;
}
