/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Response schema for bulk approve operation.
 */
export interface BulkApproveResponse {
  /** Number of atoms successfully approved */
  approved_count: number;
  /** List of atom IDs that failed to approve */
  failed_ids?: string[];
  /** Error messages for failed approvals */
  errors?: string[];
}
