/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { BulkVersionRequestReason } from './bulkVersionRequestReason';

/**
 * Request schema for bulk version operations.
 */
export interface BulkVersionRequest {
  /**
   * List of version IDs to process
   * @minItems 1
   */
  version_ids: number[];
  /** Entity type: topic or atom */
  entity_type: string;
  /** Optional reason for the action */
  reason?: BulkVersionRequestReason;
}
