/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Response schema for bulk archive operation.
 */
export interface BulkArchiveResponse {
  /** Number of atoms successfully archived */
  archived_count: number;
  /** List of atom IDs that failed to archive */
  failed_ids?: string[];
  /** Error messages for failed archives */
  errors?: string[];
}
