/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Response schema for bulk delete operation.
 */
export interface BulkDeleteResponse {
  /** Number of atoms successfully deleted */
  deleted_count: number;
  /** List of atom IDs that failed to delete */
  failed_ids?: string[];
  /** Error messages for failed deletions */
  errors?: string[];
}
