/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Request schema for bulk rejecting atoms (sets archived=true).
 */
export interface BulkRejectRequest {
  /**
   * List of atom IDs to reject (UUID strings)
   * @minItems 1
   */
  atom_ids: string[];
}
