/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { BulkVersionResponseErrors } from './bulkVersionResponseErrors';

/**
 * Response schema for bulk version operations.
 */
export interface BulkVersionResponse {
  /** Number of successfully processed versions */
  success_count: number;
  /** IDs of versions that failed to process */
  failed_ids?: number[];
  /** Error messages keyed by version ID */
  errors?: BulkVersionResponseErrors;
}
