/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Request schema for bulk archiving atoms.
 */
export interface BulkArchiveRequest {
  /**
   * List of atom IDs to archive (UUID strings)
   * @minItems 1
   */
  atom_ids: string[];
}
