/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Response schema for bulk reject operation.
 */
export interface BulkRejectResponse {
  /** Number of atoms successfully rejected */
  rejected_count: number;
  /** List of atom IDs that failed to reject */
  failed_ids?: string[];
  /** Error messages for failed rejections */
  errors?: string[];
}
