/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { ClassificationDetailTopicId } from './classificationDetailTopicId';
import type { ClassificationDetailTopicTitle } from './classificationDetailTopicTitle';
import type { ClassificationDetailReasoningBreakdown } from './classificationDetailReasoningBreakdown';

/**
 * Classification details for a message.
 */
export interface ClassificationDetail {
  confidence: number;
  reasoning: string;
  topic_id: ClassificationDetailTopicId;
  topic_title: ClassificationDetailTopicTitle;
  noise_score: number;
  urgency_score: number;
  reasoning_breakdown?: ClassificationDetailReasoningBreakdown;
}
