/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Available comparison operators for rule conditions.
 */
export type ConditionOperator = typeof ConditionOperator[keyof typeof ConditionOperator];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConditionOperator = {
  gte: 'gte',
  lte: 'lte',
  gt: 'gt',
  lt: 'lt',
  eq: 'eq',
  neq: 'neq',
  contains: 'contains',
  starts_with: 'starts_with',
  ends_with: 'ends_with',
} as const;
