/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { DashboardMetricsResponseTrends } from './dashboardMetricsResponseTrends';

/**
 * Response model for dashboard metrics.
 */
export interface DashboardMetricsResponse {
  /**
   * Average topic quality score (0-100)
   * @minimum 0
   * @maximum 100
   */
  topicQualityScore: number;
  /**
   * Percentage of messages filtered as noise
   * @minimum 0
   * @maximum 100
   */
  noiseRatio: number;
  /**
   * Classification model accuracy (0-100)
   * @minimum 0
   * @maximum 100
   */
  classificationAccuracy: number;
  /**
   * Number of currently active analysis runs
   * @minimum 0
   */
  activeAnalysisRuns: number;
  /** Trend data for each metric */
  trends: DashboardMetricsResponseTrends;
}
