/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Response schema for single embedding operation.
 */
export interface EmbedResponse {
  /** Message or Atom UUID */
  id: string;
  /** Length of embedding vector (e.g., 1536) */
  embedding_length: number;
  /** Status: completed/skipped */
  status: string;
}
