/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Extracted entities grouped by type.
 */
export interface EntitiesDetail {
  people?: string[];
  places?: string[];
  organizations?: string[];
  concepts?: string[];
}
