/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

export type FindSimilarAtomsApiV1SearchAtomsAtomIdSimilarGetParams = {
/**
 * Maximum number of results
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Minimum similarity score
 * @minimum 0
 * @maximum 1
 */
threshold?: number;
};
