/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

export type FindDuplicateMessagesApiV1SearchMessagesMessageIdDuplicatesGetParams = {
/**
 * High similarity threshold for duplicates
 * @minimum 0
 * @maximum 1
 */
threshold?: number;
};
