/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

export type GetActivityDataApiV1ActivityGetPeriod = typeof GetActivityDataApiV1ActivityGetPeriod[keyof typeof GetActivityDataApiV1ActivityGetPeriod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetActivityDataApiV1ActivityGetPeriod = {
  week: 'week',
  month: 'month',
} as const;
