/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { GetActivityDataApiV1ActivityGetPeriod } from './getActivityDataApiV1ActivityGetPeriod';

export type GetActivityDataApiV1ActivityGetParams = {
/**
 * Period type: 'week' or 'month'
 */
period?: GetActivityDataApiV1ActivityGetPeriod;
/**
 * Month (0-11, for month period)
 */
month?: number | null;
/**
 * Year (for month period)
 */
year?: number | null;
};
