/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

export type GetAutomationTrendsApiV1AutomationTrendsGetParams = {
/**
 * Time period: 7d, 30d, or 90d
 * @pattern ^(7d|30d|90d)$
 */
period?: string;
};
