/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { GetDashboardMetricsApiV1DashboardMetricsGetPeriod } from './getDashboardMetricsApiV1DashboardMetricsGetPeriod';

export type GetDashboardMetricsApiV1DashboardMetricsGetParams = {
/**
 * Time period: 'auto' (detect), 'today', or 'yesterday'
 */
period?: GetDashboardMetricsApiV1DashboardMetricsGetPeriod;
};
