/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

export type GetDashboardMetricsApiV1DashboardMetricsGetPeriod = typeof GetDashboardMetricsApiV1DashboardMetricsGetPeriod[keyof typeof GetDashboardMetricsApiV1DashboardMetricsGetPeriod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetDashboardMetricsApiV1DashboardMetricsGetPeriod = {
  auto: 'auto',
  today: 'today',
  yesterday: 'yesterday',
} as const;
