/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

export type GetMessagesApiV1MessagesGetParams = {
/**
 * Page number (starting from 1)
 * @minimum 1
 */
page?: number;
/**
 * Number of items per page
 * @minimum 1
 * @maximum 1000
 */
page_size?: number;
/**
 * Filter by author name
 */
author?: string | null;
/**
 * Filter by source name
 */
source?: string | null;
/**
 * Filter by topic ID
 */
topic_id?: string | null;
/**
 * Filter messages from this date
 */
date_from?: string | null;
/**
 * Filter messages until this date
 */
date_to?: string | null;
/**
 * Filter by importance score >= min
 */
importance_min?: number | null;
/**
 * Filter by importance score <= max
 */
importance_max?: number | null;
/**
 * Filter by noise classification (signal, noise, spam, low_quality, high_quality)
 */
classification?: string[] | null;
/**
 * Column to sort by (author_name, source_name, analyzed, sent_at)
 */
sort_by?: string | null;
/**
 * Sort order (asc or desc)
 */
sort_order?: string | null;
};
