/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { TimePeriod } from './timePeriod';

export type GetRecentTopicsApiV1TopicsRecentGetParams = {
/**
 * Time period filter (today, yesterday, week, month)
 */
period?: TimePeriod | null;
/**
 * Custom start date for filtering (ISO 8601)
 */
start_date?: string | null;
/**
 * Custom end date for filtering (ISO 8601)
 */
end_date?: string | null;
/**
 * Maximum number of topics to return
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};
