/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { GetTelegramWebhookInfoApiV1WebhookSettingsTelegramInfoGet200AnyOf } from './getTelegramWebhookInfoApiV1WebhookSettingsTelegramInfoGet200AnyOf';

export type GetTelegramWebhookInfoApiV1WebhookSettingsTelegramInfoGet200 = {[key: string]: boolean | GetTelegramWebhookInfoApiV1WebhookSettingsTelegramInfoGet200AnyOf | string};
