/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { HistoryEventAction } from './historyEventAction';
import type { HistoryEventFromTopic } from './historyEventFromTopic';
import type { HistoryEventToTopic } from './historyEventToTopic';
import type { HistoryEventAdminUser } from './historyEventAdminUser';
import type { HistoryEventReason } from './historyEventReason';

/**
 * Classification history event.
 */
export interface HistoryEvent {
  timestamp: string;
  action: HistoryEventAction;
  from_topic?: HistoryEventFromTopic;
  to_topic?: HistoryEventToTopic;
  admin_user?: HistoryEventAdminUser;
  reason?: HistoryEventReason;
}
