/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

export type HistoryEventAction = typeof HistoryEventAction[keyof typeof HistoryEventAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HistoryEventAction = {
  classified: 'classified',
  reassigned: 'reassigned',
  approved: 'approved',
  rejected: 'rejected',
} as const;
