/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Status of message ingestion job.
 */
export type IngestionStatus = typeof IngestionStatus[keyof typeof IngestionStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IngestionStatus = {
  pending: 'pending',
  running: 'running',
  completed: 'completed',
  failed: 'failed',
  cancelled: 'cancelled',
} as const;
