/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { KnowledgeExtractionRequestMessageIds } from './knowledgeExtractionRequestMessageIds';
import type { KnowledgeExtractionRequestPeriod } from './knowledgeExtractionRequestPeriod';

/**
 * Request schema for triggering knowledge extraction.
 */
export interface KnowledgeExtractionRequest {
  /** Message IDs to analyze (1-100, 10-50 recommended). Mutually exclusive with period. */
  message_ids?: KnowledgeExtractionRequestMessageIds;
  /** Period-based message selection. Mutually exclusive with message_ids. */
  period?: KnowledgeExtractionRequestPeriod;
  /** Agent Config UUID to use for extraction */
  agent_config_id: string;
}
