/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Response schema for knowledge extraction trigger.
 */
export interface KnowledgeExtractionResponse {
  /** Success message */
  message: string;
  /** Number of messages queued for extraction */
  message_count: number;
  /** Agent Config UUID used for extraction */
  agent_config_id: string;
}
