/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Message IDs to analyze (1-100, 10-50 recommended). Mutually exclusive with period.
 */
export type KnowledgeExtractionRequestMessageIds = number[] | null;
