/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

export type LinkAtomToTopicApiV1AtomsAtomIdTopicsTopicIdPostParams = {
/**
 * Display order within topic
 */
position?: number | null;
/**
 * Contextual note about the relationship
 */
note?: string | null;
};
