/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Request schema for manually linking User to TelegramProfile
 */
export interface LinkTelegramProfileRequest {
  telegram_user_id: number;
}
