/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

export type ListOllamaModelsApiV1ProvidersOllamaModelsGetParams = {
/**
 * Ollama host URL (e.g., 'http://localhost:11434')
 */
host: string;
};
