/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

export type ListAllAssignmentsApiV1AssignmentsGetParams = {
/**
 * Filter for active assignments only (is_active=true)
 */
active_only?: boolean;
/**
 * Number of records to skip for pagination
 * @minimum 0
 */
skip?: number;
/**
 * Maximum number of records to return (max: 1000)
 * @minimum 1
 * @maximum 1000
 */
limit?: number;
};
