/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

export type ListTopicsApiV1TopicsGetParams = {
/**
 * Number of records to skip
 * @minimum 0
 */
skip?: number;
/**
 * Maximum number of records to return
 * @minimum 1
 * @maximum 1000
 */
limit?: number;
/**
 * Search by name or description
 */
search?: string | null;
/**
 * Sort criteria: name_asc, name_desc, created_desc, created_asc, updated_desc
 */
sort_by?: string | null;
};
