/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

export type ListAgentsApiV1AgentsGetParams = {
/**
 * Number of records to skip
 * @minimum 0
 */
skip?: number;
/**
 * Maximum number of records to return
 * @minimum 1
 * @maximum 1000
 */
limit?: number;
/**
 * Filter for active agents only
 */
active_only?: boolean;
/**
 * Filter by provider ID
 */
provider_id?: string | null;
};
