/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { LLMProviderUpdateName } from './lLMProviderUpdateName';
import type { LLMProviderUpdateType } from './lLMProviderUpdateType';
import type { LLMProviderUpdateBaseUrl } from './lLMProviderUpdateBaseUrl';
import type { LLMProviderUpdateApiKey } from './lLMProviderUpdateApiKey';
import type { LLMProviderUpdateIsActive } from './lLMProviderUpdateIsActive';

/**
 * Schema for updating LLM provider.
 */
export interface LLMProviderUpdate {
  name?: LLMProviderUpdateName;
  type?: LLMProviderUpdateType;
  base_url?: LLMProviderUpdateBaseUrl;
  api_key?: LLMProviderUpdateApiKey;
  is_active?: LLMProviderUpdateIsActive;
}
