/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { ProviderType } from './providerType';
import type { LLMProviderCreateBaseUrl } from './lLMProviderCreateBaseUrl';
import type { LLMProviderCreateApiKey } from './lLMProviderCreateApiKey';

/**
 * Schema for creating new LLM provider.
 */
export interface LLMProviderCreate {
  name: string;
  type: ProviderType;
  base_url?: LLMProviderCreateBaseUrl;
  api_key?: LLMProviderCreateApiKey;
  is_active?: boolean;
}
