/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { ProviderType } from './providerType';
import type { LLMProviderPublicBaseUrl } from './lLMProviderPublicBaseUrl';
import type { ValidationStatus } from './validationStatus';
import type { LLMProviderPublicValidationError } from './lLMProviderPublicValidationError';
import type { LLMProviderPublicValidatedAt } from './lLMProviderPublicValidatedAt';

/**
 * Public schema for LLM provider responses.
 */
export interface LLMProviderPublic {
  id: string;
  name: string;
  type: ProviderType;
  base_url?: LLMProviderPublicBaseUrl;
  is_active: boolean;
  validation_status: ValidationStatus;
  validation_error?: LLMProviderPublicValidationError;
  validated_at?: LLMProviderPublicValidatedAt;
  created_at: string;
  updated_at: string;
}
