/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Logic operators for combining multiple conditions.
 */
export type LogicOperator = typeof LogicOperator[keyof typeof LogicOperator];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LogicOperator = {
  AND: 'AND',
  OR: 'OR',
} as const;
