/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { MessageIngestionJobPublicSourceIdentifiers } from './messageIngestionJobPublicSourceIdentifiers';
import type { IngestionStatus } from './ingestionStatus';
import type { MessageIngestionJobPublicTotalBatches } from './messageIngestionJobPublicTotalBatches';
import type { MessageIngestionJobPublicStartedAt } from './messageIngestionJobPublicStartedAt';
import type { MessageIngestionJobPublicCompletedAt } from './messageIngestionJobPublicCompletedAt';

/**
 * Public schema for ingestion job responses.
 */
export interface MessageIngestionJobPublic {
  id: number;
  source_type: string;
  source_identifiers: MessageIngestionJobPublicSourceIdentifiers;
  status: IngestionStatus;
  messages_fetched: number;
  messages_stored: number;
  messages_skipped: number;
  errors_count: number;
  current_batch: number;
  total_batches: MessageIngestionJobPublicTotalBatches;
  created_at: string;
  started_at: MessageIngestionJobPublicStartedAt;
  completed_at: MessageIngestionJobPublicCompletedAt;
}
