/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { MessageDetailSource } from './messageDetailSource';
import type { MessageDetailTelegramMessageId } from './messageDetailTelegramMessageId';

/**
 * Message metadata for inspect modal.
 */
export interface MessageDetail {
  id: string;
  content: string;
  source: MessageDetailSource;
  created_at: string;
  telegram_message_id?: MessageDetailTelegramMessageId;
}
