/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { MessageCreateRequestTelegramProfileId } from './messageCreateRequestTelegramProfileId';
import type { MessageCreateRequestAvatarUrl } from './messageCreateRequestAvatarUrl';

/**
 * Request schema for creating a message
 */
export interface MessageCreateRequest {
  external_message_id: string;
  content: string;
  sent_at: string;
  source_id: number;
  author_id: number;
  telegram_profile_id?: MessageCreateRequestTelegramProfileId;
  avatar_url?: MessageCreateRequestAvatarUrl;
}
