/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Message statistics for dashboard.
 */
export interface MessageStats {
  /**
   * Total messages in period
   * @minimum 0
   */
  total: number;
  /**
   * Messages classified as signal
   * @minimum 0
   */
  signal_count: number;
  /**
   * Messages classified as noise
   * @minimum 0
   */
  noise_count: number;
  /**
   * Signal count / total ratio
   * @minimum 0
   * @maximum 1
   */
  signal_ratio: number;
}
