/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { MessageDetail } from './messageDetail';
import type { ClassificationDetail } from './classificationDetail';
import type { AtomsDetail } from './atomsDetail';
import type { HistoryEvent } from './historyEvent';

/**
 * Full inspection response for MessageInspectModal.
 */
export interface MessageInspectResponse {
  message: MessageDetail;
  classification: ClassificationDetail;
  atoms: AtomsDetail;
  history: HistoryEvent[];
}
