/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { MessageResponseSourceName } from './messageResponseSourceName';
import type { MessageResponseAuthorName } from './messageResponseAuthorName';
import type { MessageResponseAvatarUrl } from './messageResponseAvatarUrl';
import type { MessageResponseTelegramProfileId } from './messageResponseTelegramProfileId';
import type { MessageResponseTopicId } from './messageResponseTopicId';
import type { MessageResponseTopicName } from './messageResponseTopicName';
import type { MessageResponseClassification } from './messageResponseClassification';
import type { MessageResponseConfidence } from './messageResponseConfidence';
import type { MessageResponseEmbedding } from './messageResponseEmbedding';
import type { MessageResponseImportanceScore } from './messageResponseImportanceScore';
import type { MessageResponseNoiseClassification } from './messageResponseNoiseClassification';
import type { MessageResponseNoiseFactors } from './messageResponseNoiseFactors';
import type { MessageResponseAuthor } from './messageResponseAuthor';
import type { MessageResponseCreatedAt } from './messageResponseCreatedAt';
import type { MessageResponseUpdatedAt } from './messageResponseUpdatedAt';

/**
 * Response schema for message
 */
export interface MessageResponse {
  id: string;
  external_message_id: string;
  content: string;
  sent_at: string;
  source_id: number;
  source_name?: MessageResponseSourceName;
  author_id: number;
  author_name?: MessageResponseAuthorName;
  avatar_url?: MessageResponseAvatarUrl;
  telegram_profile_id?: MessageResponseTelegramProfileId;
  topic_id?: MessageResponseTopicId;
  topic_name?: MessageResponseTopicName;
  classification?: MessageResponseClassification;
  confidence?: MessageResponseConfidence;
  analyzed?: boolean;
  embedding?: MessageResponseEmbedding;
  has_embedding?: boolean;
  importance_score?: MessageResponseImportanceScore;
  noise_classification?: MessageResponseNoiseClassification;
  noise_factors?: MessageResponseNoiseFactors;
  author?: MessageResponseAuthor;
  persisted?: boolean;
  created_at?: MessageResponseCreatedAt;
  updated_at?: MessageResponseUpdatedAt;
}
