/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { MetricTrendDirection } from './metricTrendDirection';

/**
 * Metric trend information.
 */
export interface MetricTrend {
  /** Trend direction */
  direction: MetricTrendDirection;
  /**
   * Percentage change
   * @minimum 0
   */
  change: number;
}
