/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { NoiseTrendData } from './noiseTrendData';
import type { NoiseSource } from './noiseSource';

/**
 * Noise filtering statistics for dashboard.
 */
export interface NoiseStatsResponse {
  /** Total number of messages in database */
  total_messages: number;
  /** Number of signal messages (importance > 0.7) */
  signal_count: number;
  /** Number of noise messages (importance < 0.3) */
  noise_count: number;
  /**
   * Ratio of signal to total (0.0-1.0)
   * @minimum 0
   * @maximum 1
   */
  signal_ratio: number;
  /** Number of weak signals needing review (0.3-0.7) */
  needs_review: number;
  /** 7-day trend data */
  trend: NoiseTrendData[];
  /** Top 5 noise sources */
  top_noise_sources: NoiseSource[];
}
