/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Top noise source statistics.
 */
export interface NoiseSource {
  /** Source name */
  name: string;
  /** Number of noise messages from this source */
  count: number;
}
