/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Daily noise classification trend data.
 */
export interface NoiseTrendData {
  /** Date in YYYY-MM-DD format */
  date: string;
  /** Count of high-importance messages (score > 0.7) */
  signal: number;
  /** Count of low-importance messages (score < 0.3) */
  noise: number;
  /** Count of medium-importance messages (0.3-0.7) */
  weak_signal: number;
}
