/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schema for single Ollama model information.
 */
export interface OllamaModel {
  /** Model name (e.g., 'llama3.2:latest') */
  name: string;
  /** Model size in bytes */
  size: number;
  /** Last modification timestamp */
  modified_at: string;
}
