/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { OllamaModel } from './ollamaModel';

/**
 * Response schema for Ollama models listing.
 */
export interface OllamaModelsResponse {
  /** List of available Ollama models */
  models?: OllamaModel[];
}
