/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { MessageResponse } from './messageResponse';

export interface PaginatedMessagesResponse {
  items: MessageResponse[];
  total: number;
  page: number;
  page_size: number;
  total_pages: number;
}
