/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Response schema for pending versions count.
 */
export interface PendingVersionsCountResponse {
  /** Total number of pending versions */
  count: number;
  /** Number of pending topic versions */
  topics: number;
  /** Number of pending atom versions */
  atoms: number;
}
