/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Time period type: last_24h, last_7d, last_30d, or custom
 */
export type PeriodRequestPeriodType = typeof PeriodRequestPeriodType[keyof typeof PeriodRequestPeriodType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PeriodRequestPeriodType = {
  last_24h: 'last_24h',
  last_7d: 'last_7d',
  last_30d: 'last_30d',
  custom: 'custom',
} as const;
