/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Start date for custom period (timezone-aware, required for custom)
 */
export type PeriodRequestStartDate = string | null;
