/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { PeriodRequestPeriodType } from './periodRequestPeriodType';
import type { PeriodRequestTopicId } from './periodRequestTopicId';
import type { PeriodRequestStartDate } from './periodRequestStartDate';
import type { PeriodRequestEndDate } from './periodRequestEndDate';

/**
 * Period-based message selection for knowledge extraction.
 */
export interface PeriodRequest {
  /** Time period type: last_24h, last_7d, last_30d, or custom */
  period_type: PeriodRequestPeriodType;
  /** Optional topic ID to filter messages */
  topic_id?: PeriodRequestTopicId;
  /** Start date for custom period (timezone-aware, required for custom) */
  start_date?: PeriodRequestStartDate;
  /** End date for custom period (timezone-aware, required for custom) */
  end_date?: PeriodRequestEndDate;
}
