/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectConfigCreateGlossary } from './projectConfigCreateGlossary';
import type { ProjectConfigCreateComponentsItem } from './projectConfigCreateComponentsItem';
import type { ProjectConfigCreatePriorityRules } from './projectConfigCreatePriorityRules';

/**
 * Schema for creating new project config.
 */
export interface ProjectConfigCreate {
  name: string;
  description: string;
  keywords: string[];
  glossary?: ProjectConfigCreateGlossary;
  components?: ProjectConfigCreateComponentsItem[];
  default_assignee_ids?: number[];
  pm_user_id: number;
  is_active?: boolean;
  priority_rules?: ProjectConfigCreatePriorityRules;
  version?: string;
}
