/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectConfigPublicGlossary } from './projectConfigPublicGlossary';
import type { ProjectConfigPublicComponentsItem } from './projectConfigPublicComponentsItem';
import type { ProjectConfigPublicPriorityRules } from './projectConfigPublicPriorityRules';

/**
 * Public schema for project config responses.
 */
export interface ProjectConfigPublic {
  id: string;
  name: string;
  description: string;
  keywords: string[];
  glossary: ProjectConfigPublicGlossary;
  components: ProjectConfigPublicComponentsItem[];
  default_assignee_ids: number[];
  is_active: boolean;
  priority_rules: ProjectConfigPublicPriorityRules;
  version: string;
  created_at: string;
  updated_at: string;
}
