/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectConfigUpdateName } from './projectConfigUpdateName';
import type { ProjectConfigUpdateDescription } from './projectConfigUpdateDescription';
import type { ProjectConfigUpdateKeywords } from './projectConfigUpdateKeywords';
import type { ProjectConfigUpdateGlossary } from './projectConfigUpdateGlossary';
import type { ProjectConfigUpdateComponents } from './projectConfigUpdateComponents';
import type { ProjectConfigUpdateDefaultAssigneeIds } from './projectConfigUpdateDefaultAssigneeIds';
import type { ProjectConfigUpdatePmUserId } from './projectConfigUpdatePmUserId';
import type { ProjectConfigUpdateIsActive } from './projectConfigUpdateIsActive';
import type { ProjectConfigUpdatePriorityRules } from './projectConfigUpdatePriorityRules';
import type { ProjectConfigUpdateVersion } from './projectConfigUpdateVersion';

/**
 * Schema for updating project config (partial).
 */
export interface ProjectConfigUpdate {
  name?: ProjectConfigUpdateName;
  description?: ProjectConfigUpdateDescription;
  keywords?: ProjectConfigUpdateKeywords;
  glossary?: ProjectConfigUpdateGlossary;
  components?: ProjectConfigUpdateComponents;
  default_assignee_ids?: ProjectConfigUpdateDefaultAssigneeIds;
  pm_user_id?: ProjectConfigUpdatePmUserId;
  is_active?: ProjectConfigUpdateIsActive;
  priority_rules?: ProjectConfigUpdatePriorityRules;
  version?: ProjectConfigUpdateVersion;
}
