/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectConfigUpdateComponentsAnyOfItem } from './projectConfigUpdateComponentsAnyOfItem';

export type ProjectConfigUpdateComponents = ProjectConfigUpdateComponentsAnyOfItem[] | null;
