/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { PromptType } from './promptType';
import type { PromptConfigUpdatedBy } from './promptConfigUpdatedBy';

/**
 * Prompt configuration model.
 */
export interface PromptConfig {
  prompt_type: PromptType;
  /**
   * @minLength 50
   * @maxLength 2000
   */
  prompt_text: string;
  placeholders: string[];
  updated_at: string;
  updated_by?: PromptConfigUpdatedBy;
}
