/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { ValidationError } from './validationError';

/**
 * Response model for prompt validation.
 */
export interface PromptValidationResponse {
  valid: boolean;
  errors: ValidationError[];
}
