/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { PromptType } from './promptType';

/**
 * Request model for prompt validation.
 */
export interface PromptValidationRequest {
  /**
   * @minLength 1
   * @maxLength 3000
   */
  prompt_text: string;
  prompt_type: PromptType;
}
