/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Types of prompts used in the system.
 */
export type PromptType = typeof PromptType[keyof typeof PromptType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PromptType = {
  message_scoring: 'message_scoring',
  classification: 'classification',
  knowledge_extraction: 'knowledge_extraction',
  analysis_proposal: 'analysis_proposal',
} as const;
