/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { PromptUpdateRequestUpdatedBy } from './promptUpdateRequestUpdatedBy';

/**
 * Request model for updating a prompt.
 */
export interface PromptUpdateRequest {
  /**
   * @minLength 50
   * @maxLength 2000
   */
  prompt_text: string;
  updated_by?: PromptUpdateRequestUpdatedBy;
}
