/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { ReassignRequestReason } from './reassignRequestReason';

/**
 * Request schema for topic reassignment.
 */
export interface ReassignRequest {
  new_topic_id: string;
  reason?: ReassignRequestReason;
}
