/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Structured breakdown of classification reasoning.
 */
export interface ReasoningBreakdown {
  whyTopic: string;
  whyNotNoise: string;
  keyIndicators: string[];
}
