/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { RecentTopicItemIcon } from './recentTopicItemIcon';
import type { RecentTopicItemColor } from './recentTopicItemColor';

/**
 * Schema for a recent topic with activity metrics.
 */
export interface RecentTopicItem {
  id: string;
  name: string;
  description: string;
  icon: RecentTopicItemIcon;
  color: RecentTopicItemColor;
  last_message_at: string;
  message_count: number;
  atoms_count: number;
}
