/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { RecentTopicItem } from './recentTopicItem';

/**
 * Response schema for recent topics endpoint.
 */
export interface RecentTopicsResponse {
  items: RecentTopicItem[];
  total: number;
}
