/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { RejectRequestReason } from './rejectRequestReason';
import type { RejectRequestComment } from './rejectRequestComment';

/**
 * Request schema for message rejection.
 */
export interface RejectRequest {
  reason: RejectRequestReason;
  comment?: RejectRequestComment;
}
