/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { ConditionOperator } from './conditionOperator';
import type { RuleConditionValue } from './ruleConditionValue';

/**
 * Single condition in an automation rule.

Evaluates a field from version data against an expected value
using a comparison operator.
 */
export interface RuleCondition {
  /**
   * Field path to evaluate (e.g., 'confidence', 'topic.name')
   * @minLength 1
   */
  field: string;
  /** Comparison operator to apply */
  operator: ConditionOperator;
  /** Expected value to compare against */
  value: RuleConditionValue;
}
