/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { RulePreviewResponseSampleVersionsItem } from './rulePreviewResponseSampleVersionsItem';

/**
 * Response schema showing rule preview impact.
 */
export interface RulePreviewResponse {
  /** Number of pending versions that would match this rule */
  affected_count: number;
  /** Sample of versions that would be affected (max 10) */
  sample_versions: RulePreviewResponseSampleVersionsItem[];
}
