/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { RuleCondition } from './ruleCondition';

/**
 * Request schema for previewing rule impact.
 */
export interface RulePreviewRequest {
  /**
   * List of conditions to evaluate
   * @minItems 1
   */
  conditions: RuleCondition[];
  /** Logic operator for combining conditions (AND/OR) */
  logic_operator?: string;
  /** Action that would be executed */
  action: string;
}
