/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Available automation actions.
 */
export type RuleAction = typeof RuleAction[keyof typeof RuleAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RuleAction = {
  approve: 'approve',
  reject: 'reject',
  escalate: 'escalate',
  notify: 'notify',
} as const;
