/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { ScheduledJobPublic } from './scheduledJobPublic';

/**
 * Response schema for paginated job listing.
 */
export interface ScheduledJobListResponse {
  jobs: ScheduledJobPublic[];
  total: number;
  page: number;
  page_size: number;
}
