/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { ScheduledJobCreateDescription } from './scheduledJobCreateDescription';
import type { ScheduledJobCreateTaskName } from './scheduledJobCreateTaskName';

/**
 * Schema for creating a new scheduled job.
 */
export interface ScheduledJobCreate {
  /**
   * Unique job name
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /** Job description */
  description?: ScheduledJobCreateDescription;
  /**
   * Cron expression
   * @minLength 1
   * @maxLength 100
   */
  schedule_cron: string;
  /** Job enabled status */
  enabled?: boolean;
  /** TaskIQ task name */
  task_name?: ScheduledJobCreateTaskName;
}
