/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { ScheduledJobPublicDescription } from './scheduledJobPublicDescription';
import type { ScheduledJobPublicLastRun } from './scheduledJobPublicLastRun';
import type { ScheduledJobPublicNextRun } from './scheduledJobPublicNextRun';
import type { JobStatus } from './jobStatus';
import type { ScheduledJobPublicErrorMessage } from './scheduledJobPublicErrorMessage';
import type { ScheduledJobPublicTaskName } from './scheduledJobPublicTaskName';
import type { ScheduledJobPublicCreatedAt } from './scheduledJobPublicCreatedAt';
import type { ScheduledJobPublicUpdatedAt } from './scheduledJobPublicUpdatedAt';

/**
 * Public schema for scheduled job responses.
 */
export interface ScheduledJobPublic {
  id: number;
  name: string;
  description: ScheduledJobPublicDescription;
  schedule_cron: string;
  enabled: boolean;
  last_run: ScheduledJobPublicLastRun;
  next_run: ScheduledJobPublicNextRun;
  status: JobStatus;
  error_message: ScheduledJobPublicErrorMessage;
  run_count: number;
  success_count: number;
  task_name: ScheduledJobPublicTaskName;
  created_at: ScheduledJobPublicCreatedAt;
  updated_at: ScheduledJobPublicUpdatedAt;
}
