/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { ScheduledJobUpdateName } from './scheduledJobUpdateName';
import type { ScheduledJobUpdateDescription } from './scheduledJobUpdateDescription';
import type { ScheduledJobUpdateScheduleCron } from './scheduledJobUpdateScheduleCron';
import type { ScheduledJobUpdateEnabled } from './scheduledJobUpdateEnabled';
import type { ScheduledJobUpdateTaskName } from './scheduledJobUpdateTaskName';

/**
 * Schema for updating an existing scheduled job.
 */
export interface ScheduledJobUpdate {
  /** Job name */
  name?: ScheduledJobUpdateName;
  /** Job description */
  description?: ScheduledJobUpdateDescription;
  /** Cron expression */
  schedule_cron?: ScheduledJobUpdateScheduleCron;
  /** Job enabled status */
  enabled?: ScheduledJobUpdateEnabled;
  /** TaskIQ task name */
  task_name?: ScheduledJobUpdateTaskName;
}
