/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

export type ScoreBatchApiV1NoiseScoreBatchPostParams = {
/**
 * Maximum number of messages to score
 * @minimum 1
 * @maximum 1000
 */
limit?: number;
};
