/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { AppApiV1SearchTopicSearchResult } from './appApiV1SearchTopicSearchResult';
import type { AppApiV1SearchMessageSearchResult } from './appApiV1SearchMessageSearchResult';

/**
 * Search results response.
 */
export interface SearchResultsResponse {
  topics: AppApiV1SearchTopicSearchResult[];
  messages: AppApiV1SearchMessageSearchResult[];
  total_results: number;
  query: string;
}
