/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

export type SearchTopicsSemanticApiV1SearchTopicsGetParams = {
/**
 * Search query text
 * @minLength 1
 */
query: string;
/**
 * LLM provider UUID for generating query embeddings
 */
provider_id: string;
/**
 * Maximum number of results
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Minimum similarity score
 * @minimum 0
 * @maximum 1
 */
threshold?: number;
};
