/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { SetWebhookResponseWebhookUrl } from './setWebhookResponseWebhookUrl';
import type { SetWebhookResponseError } from './setWebhookResponseError';

/**
 * Response schema for webhook setting operation
 */
export interface SetWebhookResponse {
  /** Whether operation was successful */
  success: boolean;
  /** Set webhook URL */
  webhook_url?: SetWebhookResponseWebhookUrl;
  /** Operation result message */
  message: string;
  /** Error message if failed */
  error?: SetWebhookResponseError;
}
