/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { SetWebhookRequestProtocol } from './setWebhookRequestProtocol';

/**
 * Request schema for setting webhook
 */
export interface SetWebhookRequest {
  /** Protocol for webhook URL */
  protocol: SetWebhookRequestProtocol;
  /** Host for webhook URL */
  host: string;
}
