/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Protocol for webhook URL
 */
export type SetWebhookRequestProtocol = typeof SetWebhookRequestProtocol[keyof typeof SetWebhookRequestProtocol];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SetWebhookRequestProtocol = {
  http: 'http',
  https: 'https',
} as const;
