/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Response model for sidebar notification counts.
 */
export interface SidebarCountsResponse {
  unclosed_runs: number;
  pending_proposals: number;
}
