/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { TaskConfigPublicDescription } from './taskConfigPublicDescription';
import type { TaskConfigPublicResponseSchema } from './taskConfigPublicResponseSchema';

/**
 * Public schema for task configuration responses.
 */
export interface TaskConfigPublic {
  id: string;
  name: string;
  description?: TaskConfigPublicDescription;
  response_schema: TaskConfigPublicResponseSchema;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}
