/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { TaskConfigCreateDescription } from './taskConfigCreateDescription';
import type { TaskConfigCreateResponseSchema } from './taskConfigCreateResponseSchema';

/**
 * Schema for creating new task configuration.
 */
export interface TaskConfigCreate {
  name: string;
  description?: TaskConfigCreateDescription;
  response_schema: TaskConfigCreateResponseSchema;
  is_active?: boolean;
}
