/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { TaskConfigUpdateName } from './taskConfigUpdateName';
import type { TaskConfigUpdateDescription } from './taskConfigUpdateDescription';
import type { TaskConfigUpdateResponseSchema } from './taskConfigUpdateResponseSchema';
import type { TaskConfigUpdateIsActive } from './taskConfigUpdateIsActive';

/**
 * Schema for updating task configuration.
 */
export interface TaskConfigUpdate {
  name?: TaskConfigUpdateName;
  description?: TaskConfigUpdateDescription;
  response_schema?: TaskConfigUpdateResponseSchema;
  is_active?: TaskConfigUpdateIsActive;
}
