/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { TelegramGroupInfoName } from './telegramGroupInfoName';

/**
 * Schema for Telegram group/chat information
 */
export interface TelegramGroupInfo {
  /** Telegram chat/group ID */
  id: number;
  /** Chat/group name */
  name?: TelegramGroupInfoName;
}
