/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Complete webhook URL (computed)
 */
export type TelegramWebhookConfigWebhookUrl = string | null;
