/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { TelegramWebhookConfigProtocol } from './telegramWebhookConfigProtocol';
import type { TelegramWebhookConfigWebhookUrl } from './telegramWebhookConfigWebhookUrl';
import type { TelegramWebhookConfigLastSetAt } from './telegramWebhookConfigLastSetAt';
import type { TelegramGroupInfo } from './telegramGroupInfo';

/**
 * Schema for Telegram webhook configuration
 */
export interface TelegramWebhookConfig {
  /** Protocol for webhook URL */
  protocol?: TelegramWebhookConfigProtocol;
  /** Host for webhook URL (e.g., 'example.ngrok.io') */
  host: string;
  /** Complete webhook URL (computed) */
  webhook_url?: TelegramWebhookConfigWebhookUrl;
  /** Whether webhook is active */
  is_active?: boolean;
  /** When webhook was last set */
  last_set_at?: TelegramWebhookConfigLastSetAt;
  /** Telegram groups/chats to monitor */
  groups?: TelegramGroupInfo[];
}
