/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { TelegramProfileResponseLastName } from './telegramProfileResponseLastName';
import type { TelegramProfileResponseLanguageCode } from './telegramProfileResponseLanguageCode';
import type { TelegramProfileResponseCreatedAt } from './telegramProfileResponseCreatedAt';
import type { TelegramProfileResponseUpdatedAt } from './telegramProfileResponseUpdatedAt';

/**
 * Response schema for TelegramProfile
 */
export interface TelegramProfileResponse {
  id: number;
  telegram_user_id: number;
  first_name: string;
  last_name: TelegramProfileResponseLastName;
  full_name: string;
  language_code: TelegramProfileResponseLanguageCode;
  is_bot: boolean;
  is_premium: boolean;
  user_id: number;
  source_id: number;
  created_at: TelegramProfileResponseCreatedAt;
  updated_at: TelegramProfileResponseUpdatedAt;
}
