/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Protocol for webhook URL
 */
export type TelegramWebhookConfigProtocol = typeof TelegramWebhookConfigProtocol[keyof typeof TelegramWebhookConfigProtocol];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TelegramWebhookConfigProtocol = {
  http: 'http',
  https: 'https',
} as const;
