/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Request model for triggering test task.
 */
export interface TestTaskRequest {
  /** Message ID to score */
  message_id?: number;
}
