/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Time period filter for recent topics.
 */
export type TimePeriod = typeof TimePeriod[keyof typeof TimePeriod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TimePeriod = {
  today: 'today',
  yesterday: 'yesterday',
  week: 'week',
  month: 'month',
} as const;
