/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { TopicPublic } from './topicPublic';

/**
 * Paginated response schema for topics.
 */
export interface TopicListResponse {
  items: TopicPublic[];
  total: number;
  page: number;
  page_size: number;
}
