/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { TopicCreateIcon } from './topicCreateIcon';
import type { TopicCreateColor } from './topicCreateColor';

/**
 * Schema for creating a new topic.
 */
export interface TopicCreate {
  /**
   * Topic name (must be unique)
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /**
   * Topic description
   * @minLength 1
   */
  description: string;
  /** Heroicon name (auto-selected if not provided) */
  icon?: TopicCreateIcon;
  /** Hex color code (format: #RRGGBB, auto-selected if not provided) */
  color?: TopicCreateColor;
}
