/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Hex color code (format: #RRGGBB, auto-selected if not provided)
 */
export type TopicCreateColor = string | null;
