/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { TopicVersionResponseData } from './topicVersionResponseData';
import type { TopicVersionResponseCreatedBy } from './topicVersionResponseCreatedBy';
import type { TopicVersionResponseApprovedAt } from './topicVersionResponseApprovedAt';

export interface TopicVersionResponse {
  /** Version number */
  version: number;
  /** Version snapshot data */
  data: TopicVersionResponseData;
  /** User who created version */
  created_by?: TopicVersionResponseCreatedBy;
  /** Approval status */
  approved?: boolean;
  id: number;
  topic_id: string;
  created_at: string;
  approved_at?: TopicVersionResponseApprovedAt;
}
