/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Brief topic information for message search results.
 */
export interface TopicBrief {
  id: string;
  name: string;
}
