/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { TopicUpdateName } from './topicUpdateName';
import type { TopicUpdateDescription } from './topicUpdateDescription';
import type { TopicUpdateIcon } from './topicUpdateIcon';
import type { TopicUpdateColor } from './topicUpdateColor';

/**
 * Schema for updating an existing topic.
 */
export interface TopicUpdate {
  /** Topic name (must be unique) */
  name?: TopicUpdateName;
  /** Topic description */
  description?: TopicUpdateDescription;
  /** Heroicon name */
  icon?: TopicUpdateIcon;
  /** Hex color code (format: #RRGGBB) */
  color?: TopicUpdateColor;
}
