/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Topic activity summary.
 */
export interface TopicStats {
  /**
   * Total topics count
   * @minimum 0
   */
  total: number;
  /**
   * Topics with activity in period
   * @minimum 0
   */
  active_today: number;
}
