/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { TopicPublicIcon } from './topicPublicIcon';
import type { TopicPublicColor } from './topicPublicColor';

/**
 * Public schema for topic responses.
 */
export interface TopicPublic {
  id: string;
  name: string;
  description: string;
  icon: TopicPublicIcon;
  color: TopicPublicColor;
  created_at: string;
  updated_at: string;
}
