/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Trend direction
 */
export type TrendDataDirection = typeof TrendDataDirection[keyof typeof TrendDataDirection];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TrendDataDirection = {
  up: 'up',
  down: 'down',
  neutral: 'neutral',
} as const;
