/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { TrendDataDirection } from './trendDataDirection';

/**
 * Comparison with previous period.
 */
export interface TrendData {
  /** Current period count */
  current: number;
  /** Previous period count */
  previous: number;
  /** Absolute percentage change */
  change_percent: number;
  /** Trend direction */
  direction: TrendDataDirection;
}
