/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Request schema for updating Telegram group IDs
 */
export interface UpdateTelegramGroupIdsRequest {
  /** List of Telegram group/chat IDs to monitor */
  group_ids: number[];
}
