/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { UserResponseLastName } from './userResponseLastName';
import type { UserResponseEmail } from './userResponseEmail';
import type { UserResponsePhone } from './userResponsePhone';
import type { UserResponseAvatarUrl } from './userResponseAvatarUrl';
import type { UserResponseCreatedAt } from './userResponseCreatedAt';
import type { UserResponseUpdatedAt } from './userResponseUpdatedAt';

/**
 * Response schema for User
 */
export interface UserResponse {
  id: number;
  first_name: string;
  last_name: UserResponseLastName;
  full_name: string;
  email: UserResponseEmail;
  phone: UserResponsePhone;
  avatar_url: UserResponseAvatarUrl;
  is_active: boolean;
  is_bot: boolean;
  created_at: UserResponseCreatedAt;
  updated_at: UserResponseUpdatedAt;
}
