/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { UserCreateRequestLastName } from './userCreateRequestLastName';
import type { UserCreateRequestEmail } from './userCreateRequestEmail';
import type { UserCreateRequestPhone } from './userCreateRequestPhone';
import type { UserCreateRequestAvatarUrl } from './userCreateRequestAvatarUrl';

/**
 * Request schema for creating User
 */
export interface UserCreateRequest {
  first_name: string;
  last_name?: UserCreateRequestLastName;
  email?: UserCreateRequestEmail;
  phone?: UserCreateRequestPhone;
  avatar_url?: UserCreateRequestAvatarUrl;
}
