/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Types of validation errors.
 */
export type ValidationErrorType = typeof ValidationErrorType[keyof typeof ValidationErrorType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ValidationErrorType = {
  length: 'length',
  placeholder: 'placeholder',
  syntax: 'syntax',
} as const;
