/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

/**
 * Provider validation status.
 */
export type ValidationStatus = typeof ValidationStatus[keyof typeof ValidationStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ValidationStatus = {
  pending: 'pending',
  validating: 'validating',
  connected: 'connected',
  error: 'error',
} as const;
