/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */

export interface VersionChange {
  /** Change type: values_changed, type_changes, etc. */
  type: string;
  /** JSON path to changed field */
  path: string;
  /** Previous value */
  old_value?: unknown;
  /** New value */
  new_value?: unknown;
}
