/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Pulse Radar API
 * Feel the heartbeat of your projects
 * OpenAPI spec version: 1.0.0
 */
import type { WebhookConfigResponseTelegram } from './webhookConfigResponseTelegram';

/**
 * Response schema for webhook configuration
 */
export interface WebhookConfigResponse {
  telegram?: WebhookConfigResponseTelegram;
  /** Default protocol from backend config */
  default_protocol: string;
  /** Default host from backend config */
  default_host: string;
}
